### ISSUE TITLE
Campaign Menu

### ISSUE THREAD

**Issue by IcyPerkz** [fedddddd/h2-specops-mod#23] opened 2022-12-28 15:29 UTC
When I load the mod it doesn't change menus, it's just the campaign one.

This is what it looks like when loaded
![image](https://user-images.githubusercontent.com/99234000/209835169-2cbe437e-f58d-4001-b3cc-5dd73119dcf0.png)

**Comment by Zodiac0112** [comment] 2023-01-03 13:35
I have the same problem, thought I was missing something.

**Comment by fedddddd** [comment] 2023-01-03 15:46
Dupe of #22

**Closed by fedddddd** 2023-01-03 15:46 UTC
